# Generated by Django 4.2.4 on 2024-11-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comment_id_alter_creditcode_id_and_more'),
    ]

    operations = [
    ]
