# Generated by Django 4.2.4 on 2024-11-09 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20241108_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
