# Generated by Django 4.2.4 on 2024-11-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0003_merge_20190815_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='numero',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
